#!/bin/bash

# bash setting for MacOSx

test -f ~/.bashrc && source ~/.bashrc 
# SET COLOR
function config_bash_color()
{
    export CLICOLOR=1
    export TERM=xterm-256color
    export PS1='\[\033[00;31m\]\u@MacOSx\[\033[00m\]:\[\033[00;35m\]\w\[\033[00m\]\$ '  
}

# SET SSH COPY TO RASP4
function cp2rasp4()
{
    if [ $# -lt 1 ];then
        echo "error,there's not enough input"
        return 1
    else
        scp "$1" huangmianbo@rasp4:~/
    fi
}

# PATH SETTING
function config_path()
{
    PATH=/usr/local/bin:$PATH;
    PATH=/usr/local/Cellar/vim/8.1.1501/bin:$PATH;
    PATH=/usr/local/Cellar/macvim/8.1-156/bin:$PATH;
    PATH=/usr/local/Cellar/git/2.22.0/bin:$PATH;
    PATH=/usr/local/texlive/2019/bin/x86_64-darwin:$PATH
    PATH=/usr/local/opt/icu4c/bin:$PATH
    PATH=/usr/local/opt/icu4c/sbin:$PATH
    PATH=/usr/local/opt/qt/bin:$PATH
    PATH=/Users/huangmianbo/Software/V2RayX.app/Contents/MacOS/:$PATH
    PATH=/Users/huangmianbo/Software/Qt5.13.1/5.13.1/clang_64/bin/:$PATH
    export PATH
}

# PKG CONFIG PATH
function config_pkg_path()
{
    PKG_CONFIG_PATH=/usr/local/Cellar/libidn2/2.2.0/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/ncurses/6.1/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/nettle/3.4.1/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/mpfr/4.0.2/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/python/3.5.7/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/python/3.7.3/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/libyaml/0.2.2/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/readline/8.0.0_1/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/sqlite/3.28.0/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/zlib/1.2.11/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/xz/5.2.4/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/lua/5.3.5_1/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/curl/7.65.1/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/libtasn1/4.13/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/libevent/2.1.10/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/unbound/1.9.1_1/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2r/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/p11-kit/0.23.16.1/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/ruby/2.6.3/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/Cellar/gnutls/3.6.8/lib/pkgconfig:$PKG_CONFIG_PATH;
    PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH
    PKG_CONFIG_PATH=/usr/local/opt/qt/lib/pkgconfig:$PKG_CONFIG_PATH

    export PKG_CONFIG_PATH
}

# VLC 
function _vlc()
{
    /Applications/VLC.app/Contents/MacOS/VLC $* &> /dev/null & 
}

function _qtime()
{
    /Applications/QuickTime\ Player.app/Contents/MacOS/QuickTime\ Player $PWD/$* &> /dev/null &
}

# PDFGURU
function _pdfguru()
{
     /Applications/PDFGuru.app/Contents/MacOS/PDFGuru $1  &> /dev/null &
}

# Document Viewer
function _previewer()
{
    /Applications/Preview.app/Contents/MacOS/Preview $PWD/$1  &>  /dev/null &
}

# QT Creator 
function _qt_creator()
{
    /Users/huangmianbo/Qt5.13.1/Qt\ Creator.app/Contents/MacOS/Qt\ Creator &> /dev/null &
}

# evince
function _evince()
{
    if [ "$1" == "--help" ] || [ "$1" == "-h" ] || [ "$1" == "--help-all" ];then
        evince --help
    else
        evince $1 &> /dev/null &
    fi
}

# back document
function _backup_documents()
{
    pushd . > /dev/null
    
    cd ~/Documents/10-github-documents

    ./update_documents_from_local.sh

    check=`git status | grep "modified:"`
    echo check is $check

    if [ -z "$check" ];then
        echo nothing to commit from macosx to github !!
    else
        files=`echo $check | awk -F":" '{print $2}'`
        for file in $files
        do
            git add $file
        done
        git commit -m "update documents from $HOSTNAME"
        git push -u github master
    fi

    popd > /dev/null
}

function _backup_config()
{
    pushd . > /dev/null

    cd ~/Documents/11-configs-from-github
    
    ./update_config_file.sh

    check=`git status | grep "modified:"`

    if [ -z "$check" ];then
        echo nothing to commit from macosx to github !!
    else
        files=`echo $check | awk -F":" '{print $2}'`
        for file in $files
        do
            git add $file
        done
        git commit -m "update config files from $HOSTNAME"
        git push -u github master
    fi

    popd > /dev/null
}

# synctask warrior
function _synctask()
{

    if [ "$1" == "--help" ];then
       echo "synctask up : upload task to the remote origin" 
       return 0 
    fi

    if [ "$1" == "up" ];then
        pushd . &&  \
        cd ~ && \
        git push -u harddrive master && \
        popd
        return 0
    fi

    if [ "$1" == "down" ];then
        pushd . &&  \
        cd ~ && \
        git pull origin master && \
        popd
        return 0
    else
        echo "error unknown option"
        return 1
    fi 
}

# md2pdf
function _md2pdf()
{
    file=$1
    if [ ! -f "$file" ];then
        echo "error,there's no such file $file"
    fi
    pdffile=${file/.md/.pdf}
    pandoc $file -o $pdffile
}

# _gvim
function _gvim()
{
    gvim $* &> /dev/null &
}

# check other task warrior
function _other_task()
{
    export TASKDATA=~/Documents/12-cygwin64-config-t580/.task
    task rc:~/Documents/12-cygwin64-config-t580/.task $*
    export TASKDATA="~/.task"
}

# Config for Alias
function config_alias()
{
    alias c='clear'
    alias vi='vim --noplugin'
    alias gvim='_gvim'
    alias rm='rm -iv'
    alias reload='source ~/.bash_profile'
    alias config='vim ~/.bash_profile'
    # alias t430='ssh huangmianbo@192.168.50.28'
    alias t430='ssh huangmianbo@ThinkPad-T430'
    alias vlc='_vlc'
    alias qtime='_qtime'
    alias rdp='/Applications/Microsoft\ Remote\ Desktop.app/Contents/MacOS/Microsoft\ Remote\ Desktop &'
    alias tl='task list'
    # alias pdf='zathura'
    # alias pdf='_pdfguru'
    alias pdf='_previewer'
    alias ..='cd ../'
    alias ...='cd ../../'
    alias ....='cd ../../../'
    alias grep='grep --color=auto'
    alias temp='/usr/local/bin/osx-cpu-temp'
    alias gigabyte='ssh mianb@gigabyte-brix'
    # alias gigabyte='ssh mianb@192.168.50.116'
    alias rasp3='ssh huangmianbo@192.168.50.102'
    alias rasp3-xeno3='ssh pi@raspberrypi3-xeno3'
    alias rasp4='ssh huangmianbo@raspberrypi4'
    alias pi4='ssh pi@raspberrypi4'
    # alias rasp4='ssh huangmianbo@192.168.50.73'
    alias beaglebone='ssh huangmianbo@192.168.50.204'
    alias debian@beaglebone='ssh debian@192.168.50.204'
    alias pi@rasp4='ssh debian@raspberrypi4'
    alias git@t430='ssh git@thinkpad-t430'
    alias vpn='/Applications/ShadowsocksX-NG-R8.app/Contents/MacOS/ShadowsocksX-NG &'
    alias gdb='sudo gdb -q'
    alias lldb='sudo lldb'
    alias synctask='pushd . && cd ~ && git pull origin master && popd'
    alias ~='cd $HOME'
    alias poweroff='sudo shutdown -h now'
    alias md2pdf='_md2pdf'
    alias poweroff='sudo shutdown -h now'
    alias qt='_qt_creator'
    alias v2ray='V2RayX &> /dev/null &'
    alias cpptags='ctags -R --c++-kinds=+p --fields=+iaS --extra=+q'
    alias mv='mv -iv'
    alias bdoc='_backup_documents'
    alias bconfig='_backup_config'
    alias doc='cd ~/documents'
    alias task2='_other_task'
}

set completion-ignore-case On

if [ "$SHELL" = "/bin/bash" ];then   
    config_bash_color
fi

config_path
config_pkg_path
config_alias

export EDITOR=vim
export LDFLAGS="-L/usr/local/opt/qt/lib":$LDFLAGS
export CPPFLAGS="-I/usr/local/opt/qt/include":$CPPFLAGS
export QTDIR='/Users/huangmianbo/Software/Qt5.13.1/5.13.1/clang_64/'
export DQTDIR='/Users/huangmianbo/Software/Qt5.13.1/5.13.1/Src/'
set -o vi



tl
